import React from 'react';
import { createRoot } from 'react-dom/client';

// Load the pre-built klsh bundle so the global `window.klsh` exists *before*
// any other modules (e.g. text2json) execute.  The path is relative to this
// file (webui/src) – two levels up resides dist/klsh.js, generated by
// `npm run build` at the repository root.
import '../../dist/klsh.js';

import { PipelineProvider } from './store/pipeline.jsx';
import App from './App.jsx';

// Bootstrap React application and wrap it in the Zustand provider so that the
// pipeline JSON store is available to the entire component tree.

const container = document.getElementById('root');
const root = createRoot(container);

root.render(
  <React.StrictMode>
    <PipelineProvider>
      <App />
    </PipelineProvider>
  </React.StrictMode>
);
