// Auto-generated by build.js. Do not edit.
const echo = require('./core/echo').main;
const parse_args = require('./core/parse_args').main;
const parse_klsh = require('./core/parse_klsh').main;

module.exports = {
  echo,
  parse_args,
  parse_klsh,
};
